### ISSUE TITLE
got error on breaking news request (view on github for screenshot)

### ISSUE THREAD

**Issue by gelsto** [chubbyoptometrist/ArrogantStarfish#49]
![screen shot 2015-11-24 at 5 57 31 pm](https://cloud.githubusercontent.com/assets/14044431/11389042/e4d64148-92f0-11e5-9978-59637660933b.png)
Refreshed and it was fine, IDK what happened but if this means something to you...

**Comment by arbitragedlife** [comment]
Edge case from the way I'm parsing the data, I'll play around with Postman and see if this pops up again.
